2020-11-22 19:06:22,154 INFO    MainThread:11439 [wandb_setup.py:_flush():68] setting env: {}
2020-11-22 19:06:22,155 INFO    MainThread:11439 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-11-22 19:06:22,155 INFO    MainThread:11439 [wandb_setup.py:_flush():68] setting login settings: {}
2020-11-22 19:06:22,156 INFO    MainThread:11439 [wandb_init.py:_log_setup():302] Logging user logs to /home/alrawis/EIN-SELD/seld/wandb/run-20201122_190621-1g2u950u/logs/debug.log
2020-11-22 19:06:22,156 INFO    MainThread:11439 [wandb_init.py:_log_setup():303] Logging internal logs to /home/alrawis/EIN-SELD/seld/wandb/run-20201122_190621-1g2u950u/logs/debug-internal.log
2020-11-22 19:07:06,407 WARNING MainThread:11439 [wandb_init.py:init():589] interrupted
Traceback (most recent call last):
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 569, in init
    run = wi.init()
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 404, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 536, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 527, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 440, in _communicate
    return future.get(timeout)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 58, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/alrawis/miniconda3/envs/ein/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2020-11-22 19:07:06,745 INFO    MainThread:11439 [internal.py:handle_exit():138] Internal process exited
